### ISSUE TITLE
Make signing commits optional

### ISSUE THREAD

**Issue by holtkamp** [woohoolabs/releaser#2]
nice tool! Small suggestion: I am not really interested (yet) in getting `gpg` up and running to sign my commits, but still would like to experiment with this tool to improve my workflow / force me to write proper CHANGELOG entries. 

Making the "signing commit" part optional might be an idea?

As in "drop the `-s` in 

https://github.com/woohoolabs/releaser/blob/f525aab5b2855bdf3ce53a79d426be7af0bd372e/bin/releaser#L85

**Comment by kocsismate** [comment]
I am OK to make signing optional, but I'd prefer the other way around: the default should be signing, and it should be omitted if let's say the `--without-signing` or `--no-signing` option is provided.

It would be really cool if you could provide a PR for this. If it is not possible, I can also do it in the future when my workload decreases.

**Comment by holtkamp** [comment]
Sure! I agree with making signing the default. 

I will give it a try and come up with a PR, only bash is quite new for me and my time also seems structurally short, haha. No hurry with this, nice task for a rainy Sunday...

**Comment by kocsismate** [comment]
@holtkamp Done in v1.2. Please try it :)
